const defaultDelay = 2500;
const defaultPostDelay = 1000;
const defaultWidth = 820;

const siteActions = [
  {
    name: "dailymail.co.uk",
    clicks: ["//button[text()='Got it']", "//div[@id='smartBanner']/a", "//div[@id='closeButton']"],
    removes: [
      "//div[@id='chromelessPlayer']",
      "//div[@id='vjs_video_3']",
      "//div[contains(@class,'billboard-container')]",
    ],
    delay: 4000,
    retryCount: 2,
    width: 980,
  },
  {
    name: "independent.co.uk",
    clicks: [
      "//button[contains(@class,'sticky-ad-close-button-press')]",
      "//button[contains(@class,'pn-template__close')]",
    ],
    removes: ["//div[@id='stickyFooterRoot']", "//div[child::div[child::div[@data-tile-name='top_banner']]]"],
    width: 768,
  },
  {
    name: "mirror.co.uk",
    clicks: ["//button[text()='I accept']"],
    removes: [
      "//reach-billboard[contains(@class,'ad-placeholder--top')]",
      "//reach-billboard[contains(@class,'ad-placeholder--bottom')]",
      "//div[@id='takeover']",
    ],
    delay: 4000,
    width: 832,
  },
  {
    name: "telegraph.co.uk",
    removes: [
      "//div[contains(@class,'martech-footer-overlay')]",
      "//div[@id='advert_tmg_ban']",
      "//div[contains(@class,'martech-modal-component-overlay')]",
    ],
    delay: 4000,
  },
  { name: "thesun.co.uk", removes: ["//div[contains(@class,'billboard')]"], width: 700 },
  {
    name: "theguardian.com",
    removes: [
      "//div[contains(@class,'site-message--banner')]",
      "//gu-island[@name='StickyBottomBanner']",
      "//div[contains(@class,'top-banner-ad-container')]",
    ],
    width: 980,
    tabletWidth: 740,
    desktopWidth: 980,
  },
  {
    name: "ft.com",
    clicks: ["//a[contains(.,'Accept & continue')]", "//button[contains(@class,'o-banner__close')]"],
    removes: ["//div[@data-o-ads-name='top-desktop']"],
    width: 820,
    desktopWidth: 1024,
  },
  { name: "bbc.com", clicks: ["//button/p[text()='Consent']", "//button/span[text()='Yes, I agree']"] },
  {
    name: "washingtonpost.com",
    clicks: ["//button[text()='I accept']", "//button[text()='Got it']", "//button[@aria-label='close']"],
    removes: ["//wp-ad[@id='slug_leaderboard_1']", "//div[contains(@class,'adslot-c')]"], //, "//div[contains(@class,'video-live-bar')]"],
    styles: [{ xpath: "//main[@id='main-content']", value: { "margin-top": "32px" } }],
    retryCount: 2,
    delay: 4000,
    width: 900,
  },
  {
    name: "nytimes.com",
    clicks: ["//button[text()='Accept']"],
    removes: [
      "//div[child::div[child::div[@data-testid='StandardAd']]]",
      // "//div[child::div[child::div[contains(@class,'dfp-ad-top-wrapper')]]]",
    ],
    // retryCount: 2,
  },
  {
    name: "edition.cnn.com",
    clicks: ["//button[text()='Accept All']"],
    removes: ["//div[@id='header-wrap']"],
    width: 960,
  },
  { name: "foxnews.com", clicks: ["//div[@aria-label='Close']"], removes: ["//div[contains(@class,'ad-container')]"] },
  {
    name: "wsj.com",
    removes: ["//div[@id='cx-candybar']", "//div[child::div[@id='wrapper-AD_PUSH']]"],
    styles: [
      { xpath: "//div[contains(@class,'WSJTheme--margin-bottom')]", value: { "margin-bottom": "0" } },
      { xpath: "//div[contains(@class,'style--padding-top-large')]", value: { "border-top": "none" } },
    ],
    width: 980,
    delay: 4000,
    postDelay: 3000,
  },
  {
    name: "apnews.com",
    clicks: ["//button[text()='Accept All Cookies']"],
    removes: ["//div[contains(@class,'Leaderboard')]"],
    delay: 4000,
    desktopWidth: 1025,
  },
  {
    name: "vox.com",
    clicks: ["//button[@id='privacy-consent-button']", "//button[contains(@class,'c-breaking-news__close')]"],
  },
  {
    name: "eu.usatoday.com",
    clicks: ["//button[text()='Accept All']"],
    removes: ["//partner-high-impact[contains(@class,'spacer-large')]"],
    desktopWidth: 960,
  },
  { name: "latimes.com", clicks: ["//button[text()='Close']"] },
  {
    name: "cnbc.com",
    clicks: ["//button[text()='I Accept']"],
    removes: ["//div[child::div[child::div[contains(@class,'TopBanner-container')]]]"],
    delay: 4000,
    retryCount: 2,
    postDelay: 2000,
    width: 1020,
    desktopWidth: 1020,
  },
  {
    name: "bloomberg.com",
    removes: ["//div[contains(@class,'canopy-container')]"],
    width: 780,
    desktopWidth: 1020,
  },
  {
    name: "hbl.fi",
    clicks: ["//button/p[text()='Jag godkänner']"],
    removes: ["//div[contains(@class,'mosaico-ad__parade')]", "//div[contains(@class,'mosaico-ad__top-parade')]"],
    desktopWidth: 1000,
  },
  { name: "hs.fi", clicks: ["//button[text()='OK']"], removes: ["//div[@data-ad-position='top']"], width: 780 },
  {
    name: "bt.dk",
    clicks: ["//button[text()='Tillad alle']"],
  },
  {
    name: "ekstrabladet.dk",
    clicks: ["//button[text()='Tillad alle']"],
    removes: ["//div[@id='ebbanner_megaboard_top']"],
    width: 940,
  },
  {
    name: "politiken.dk",
    clicks: [
      "//button[text()='Tillad alle']",
      "//div[@id='topscroll']/div[2]",
      "//div[contains(@class,'adnm-scroll-down-btn')]",
      "//a[text()='Fortryd']",
    ],
    removes: ["//div[contains(@class,'sticky-bottom')]", "//div[contains(@class,'ad--horseshoe')]"],
    delay: 3500,
    retryCount: 2,
    width: 960,
  },
  { name: "berlingske.dk", clicks: ["//button[text()='Tillad alle']"] },
  {
    name: "lemonde.fr",
    clicks: ["//button[text()='Accept']", "//button[contains(.,'Accepter et continuer')]"],
    width: 770,
  },
  {
    name: "lefigaro.fr",
    clicks: ["//div[@id='appconsent']/iframe | //span[text()='Accept all']", "//button[@title='Fermer le bandeau']"],
    removes: ["//div[contains(@class,'fig-ad-content')]"],
  },
  {
    name: "france24.com",
    clicks: ["//button[@id='didomi-notice-agree-button']", "//button[contains(@class,'a-close-button')]"],
    removes: ["//div[contains(@class,'o-ad-container--banner-top')]"],
  },
  {
    name: "telegraaf.nl",
    clicks: ["//button[@id='didomi-notice-agree-button']", "//button[text()='Ja, prima!']"],
    removes: [
      "//div[contains(@class,'SectionPage__bannerWrapper--position-0')]",
      "//div[contains(@class,'MainCuratedTeasersLayout__banner')]",
    ],
    retryCount: 2,
  },
  {
    name: "ad.nl",
    removes: ["//div[contains(@class,'advertising-container-top')]", "//anchor[contains(@class,'sleeknote-anchor')]"],
    postDelay: 6000,
    // waitForNavigation: true,
  },
  {
    name: "corriere.it",
    clicks: [
      "//iframe[@id='_cpmt-iframe'] | //button[text()='Agree']",
      "//button[@aria-label='Close']",
      "//div[@id='introDfp_close']",
    ],
    removes: ["//div[@id='rcsad_Position7']", "//div[@id='rcsad_TopLeft_wrapper']"],
    styles: [{ xpath: "//header[@id='l-header']", value: { "margin-bottom": "0" } }],
    retryCount: 2,
    // postDelay: 6000,
    width: 1024,
    // waitForNavigation: true,
  },
  {
    name: "repubblica.it",
    clicks: ["//button[text()='Accetta']"],
    removes: ["//div[@id='adv-TopLeft']", "//div[child::a[child::div[@id='adv_Skin']]]"],
    styles: [
      // { xpath: "//div[@id='adv-TopLeft']", value: { display: "none !important" } },
      // { xpath: "//div[@class='gd-row'][1]", value: { "max-height": "42px" } },
    ],
  },
  { name: "lastampa.it", clicks: ["//button[text()='Accetta']"] },
  {
    name: "gazzetta.it",
    clicks: [
      "//iframe[@id='_cpmt-iframe'] | //button[text()='Agree']",
      "//div[@id='closeBtnP7']",
      "//p[text()='CHIUDI']",
    ],
    removes: ["//div[@class='wrapper is-paddingless']", "//div[@id='rcsad_TopLeft_container']"],
    styles: [{ xpath: "//header[@id='l-header']", value: { "margin-bottom": "8px" } }],
    delay: 4000,
    postDelay: 6000,
    retryCount: 2,
    width: 1024,
  },
  { name: "vg.no", removes: ["//div[@id='advert-topboard']"], width: 1010 },
  { name: "dagbladet.no", clicks: ["//button[text()='Jeg forstår']"], removes: ["//div[@id='ad-topbanner1']"] },
  {
    name: "aftenposten.no",
    removes: [
      "//div[@id='topboard']",
      "//div[@id='top-ads-container']",
      "//div[@id='push-down-banner']",
      "//div[@id='stripe-wrapper']",
      "//div[child::div[child::article[contains(@class,'brandstudio-premium-content-widget')]]]",
    ],
  },
  {
    name: "nettavisen.no",
    clicks: ["//button[text()='OK – jeg forstår']", "//amedia-privacybox-button[@class='lp_privacy_ok']"],
    removes: ["//div[contains(@class,'maelstrom-topbanner')]", "//div[@id='front2']", "//amedia-privacybox"],
  },
  {
    name: "finansavisen.no",
    clicks: ["//a[text()='OK, jeg forstår!']"],
    removes: ["//div[@data-banner]"],
    styles: [{ xpath: "(//div[contains(@class,'o-layout')])[2]", value: { display: "none" } }],
    delay: 3500,
  },
  {
    name: "zeit.de",
    clicks: ["//button[contains(@class,'paywall-footer__btn-close')]"],
    removes: ["//div[@data-ct-area='topnav-sticky']"],
    delay: 4000,
    desktopWidth: 1004,
  },
  {
    name: "bild.de",
    clicks: ["//a[text()='OK, jeg forstår!']"],
    removes: ["//div[contains(@class,'inactivity__wrapper')]", "//div[@id='superbannerWrapper']"], //, "//div[contains(@class,'o-layout')]"],
    width: 1024,
  },
  {
    name: "t-online.de",
    removes: [, "//section[@data-testid='InactivityLayer.ModalView']"],
    postDelay: 4000,
  },
  {
    name: "spiegel.de",
    clicks: ["//button[@aria-label='Schließen']"],
    width: 770,
  },
  {
    name: "aftonbladet.se",
    clicks: [
      "//button/img[@alt='Stäng']",
      "//span[text()='TILL AFTONBLADET']",
      "//img[@alt='Scrolla ner till Aftonbladet']",
      "//button/img[@alt='Stäng annonsen']",
    ],
    removes: ["//div[contains(@class,'page-layout-supertop')]"],
    retryCount: 2,
  },
  {
    name: "expressen.se",
    clicks: [
      "//button[@id='didomi-notice-agree-button']",
      "//button[contains(@class,'campaign__close')]",
      "//span[contains(@class,'fullpage-ad__close')]",
      "//button[contains(@class,'tapet-close-button')]",
    ],
    removes: ["//div[@data-slot-name='panorama']"],
    width: 1016,
  },
  {
    name: "gp.se",
    clicks: [
      "//input[@value='Jag förstår']",
      "//div[contains(@class,'dy-lb-close')]",
      "//div[contains(@class,'adnm-scroll-down-btn')]",
    ],
    removes: ["//div[@data-key='adl--stage']", "//div[@id='panorama_1']"],
    styles: [{ xpath: "//main[contains(@class,'o-grid__main')]", value: { "margin-top": "16px" } }],
  },
  {
    name: "dn.se",
    clicks: ["//button[@id='didomi-notice-agree-button']", "//button[@aria-label='Stäng']"],
    removes: ["//div[contains(@class,'panorama')]", "//div[@id='rich-media-ads']"],
    width: 1024,
  },
  {
    name: "di.se",
    // cookies: [{ domain: "www.di.se", name: "channel", value: "tablet" }],
    clicks: [
      "//button[@id='didomi-notice-agree-button']",
      "//button[text()='Godkänn och stäng']",
      "//div[contains(@class,'ad-fullpage__info')]",
    ],
    removes: ["//div[contains(@class,'panorama')]"],
    postDelay: 4000,
    width: 1024,
  },
  {
    name: "svd.se",
    clicks: ["//span[contains(@class,'Notification-close-button')]"],
    removes: ["//div[contains(@class,'Container--ad Container--ad-panorama')]"],
  },
  {
    name: "sydsvenskan.se",
    clicks: ["//button[@id='didomi-notice-agree-button']", "//span[contains(@class,'ad-welcome__arrow')]"],
  },
  {
    name: "dagensnaringsliv.se",
    clicks: ["//button[text()='Jag godkänner']"],
  },
  {
    name: "breakit.se",
    clicks: ["//button[text()='JAG GODKÄNNER']", "//iframe[@aria-label='Advertisement'] | //div[@id='close-x']"],
    removes: ["//div[contains(@class,'Home_layout__topAds')]"],
    retryCount: 2,
    delay: 3000,
    width: 1000,
  },
  {
    name: "realtid.se",
    clicks: [], //"//span[text()='Accept all']"],
    removes: ["//div[@id='cmpwrapper']", "//div[contains(@class,'realtid-add--header')]"],
  },
  {
    name: "resume.se",
    clicks: ["//button[@id='didomi-notice-agree-button']", "//p[contains(.,'Detta är en annons, vidare till')]"],
    removes: [
      "//div[child::div[@id='scope-panorama']]",
      "//div[child::div[@id='scope-module-1']]",
      "//div[contains(@class,'tippy-popper')]",
    ],
    retryCount: 2,
  },
  {
    name: "dagenssamhalle.se",
    clicks: ["//button[@id='didomi-notice-agree-button']"], // , "//span[@id='close']"
    removes: [
      "//div[contains(@class,'tippy-popper')]",
      "//div[child::div[@id='scope-panorama']]",
      "//div[child::div[@id='scope-module-1']]",
    ],
    retryCount: 2,
    postDelay: 3000,
    width: 960,
  },
  {
    name: "vk.se",
    clicks: [
      "//div[@id='gdpr-module-group-understand-button']",
      "//a[text()='Stäng annons']",
      "//button[contains(@class,'button-hide')]",
    ],
    removes: [
      "//div[@data-track-id='layout-item-0.panoramaAd']",
      "//div[contains(@class,'vkmui-FlexVerticalCentered')]",
    ],
    width: 1024,
  },
  {
    name: "privataaffarer.se",
    clicks: ["//div[contains(.,'Acceptera alla')]"],
  },
  {
    name: "nyheter24.se",
    clicks: [
      "//p[text()='Jag samtycker']",
      "//button[@id='webpushes_pop_cancel']",
      "//div[contains(@class,'jpx-fi-close')]",
    ],
    delay: 4000,
    width: 1180,
  },
  {
    name: "dalademokraten.se",
    clicks: ["//button[@id='didomi-notice-agree-button']"], //,"//button[contains(@class,'button-hide')]"],
    removes: ["//div[contains(@class,'shelf--panorama')]", "//triggerbee-widget"],
    styles: [{ xpath: "//div[contains(@class,'block--top')]", value: { "padding-top": "0" } }],
    width: 1000,
    desktopWidth: 1000,
  },
  {
    name: "hd.se",
    clicks: ["//button[@id='didomi-notice-agree-button']"],
    removes: ["//div[contains(@class,'shelf--panorama')]", "//triggerbee-widget"],
    styles: [{ xpath: "//div[contains(@class,'block--top')]", value: { "padding-top": "0" } }],
    width: 1000,
    desktopWidth: 1000,
  },
  {
    name: "e24.no",
    removes: ["//div[@id='ad-topboard']"],
  },
  {
    name: "hallandsposten.se",
    clicks: ["//input[@value='Jag förstår']"],
    removes: ["//div[@id='panorama_1']"],
    styles: [{ xpath: "//main[contains(@class,'o-grid__main')]", value: { "margin-top": "16px" } }],
  },
  {
    name: "sweclockers.com",
    clicks: ["//button[text()='Acceptera allt']"],
    removes: ["//div[@id='panorama-1']"],
  },
  {
    name: "idg.se",
    clicks: ["//button[text()='Godkänn']"],
    postDelay: 7500,
  },
  {
    name: "nyteknik.se",
    clicks: ["//a/img[@alt='close']"], // "//button[contains(@class,'button-hide')]"],
    removes: [
      "//div[child::div[child::div[@id='nyteknik_desktop-panorama-mega']]]",
      "//triggerbee-widget",
      "//div[child::span[@data-set='panorama']]",
    ],
    retryCount: 2,
    delay: 3000,
    desktopWidth: 992,
  },
  {
    name: "svt.se",
    clicks: ["//input[@value='Jag förstår']"],
  },
  {
    name: "nzz.ch",
    clicks: ["//span[text()='Alle Akzeptieren']", "//span[@type='close'][@role='button']"],
    removes: ["//div[contains(@class,'resor--maxiboard')]"],
  },
  {
    name: "20min.ch",
    clicks: ["//button[text()='Akzeptieren']"],
    removes: ["//*[child::div[@id='prime__inside-top']]", "//*[child::div[@id='default__outside-welcome']]"],
    delay: 4000,
  },
  {
    name: "elpais.com",
    clicks: ["//span[text()='Accept']"],
    removes: ["//div[contains(@class,'ad-giga-1')]"],
    styles: [
      {
        xpath: "//div[@id='ctn_head']",
        value: { "min-height": "9rem" },
      },
      {
        xpath: "//div[@class='x _pr x-nf _g x-p']",
        value: { padding: "0 0 2rem" },
      },
    ],
    width: 780,
  },
  {
    name: "mbl.is",
    clicks: ["//a[text()='Loka']"],
    removes: ["//div[contains(@class,'yfirhaus-ad')]"],
    styles: [
      {
        xpath: "//div[contains(@class,'main-header')]",
        value: { "margin-top": "0", "margin-bottom": "0 !important" },
      },
    ],
    width: 780,
  },
  {
    name: "krone.at",
    clicks: ["//span[text()='Zustimmen & Weiter']"],
    removes: ["//div[contains(@class,'c_floating-player')]"],
    width: 955,
  },
  {
    name: "heute.at",
    clicks: ["//button[text()='Akzeptieren']"],
    removes: ["//div[@id='inside-full-top']"],
    retryCount: 2,
    width: 970,
  },
  {
    name: "bangkokpost.com",
    clicks: ["//a[text()='Accept and close']"],
    removes: ["//div[contains(@class,'ads-leaderboard')]"],
    width: 992,
    desktopWidth: 992,
  },
  {
    name: "aljazeera.com",
    clicks: ["//button[text()='Allow All']"],
    removes: ["//div[contains(@class,'container--ads-leaderboard-mid')]"],
  },
  {
    name: "hln.be",
    removes: [
      "//li[contains(@class,'sixpack__advertisement-tile')]",
      "//div[contains(@class,'advertising-container-top')]",
    ],
    retryCount: 2,
    postDelay: 4000,
  },
];

const iframeActions = [
  { name: "tcf2.telegraph.co.uk", clicks: ["//button[@title='Accept']"] },
  { name: "accounts.google.com", clicks: ["//div[@aria-label='Logga in med Google']//div[@id='close']"] },
  { name: "cmp.cdn.thesun.co.uk", clicks: ["//button[text()='Fine By Me!']"] },
  { name: "sourcepoint.theguardian.com", clicks: ["//button[text()=\"Yes, I’m happy\"]"] }, // prettier-ignore
  { name: "cdn.privacy-mgmt.com", clicks: ["//button[text()='YES, I AGREE']", "//button[text()='OK']"] },
  { name: "cmp.ad.nl", clicks: ["//button[text()='Akkoord']"] },
  { name: "cmp.vg.no", clicks: ["//button[text()='Jeg forstår']"] },
  { name: "cmp.aftenposten.no", clicks: ["//button[text()='Jeg forstår']"] },
  { name: "cmp.e24.no", clicks: ["//button[text()='Jeg forstår']"] },
  { name: "cmp2.bild.de", clicks: ["//button[text()='Alle akzeptieren']"] },
  { name: "consent.t-online.de", clicks: ["//button[text()='AKZEPTIEREN UND WEITER']"] },
  { name: "sp-spiegel-de.spiegel.de", clicks: ["//button[contains(.,'Accept and continue')]"] },
  { name: "cmp.aftonbladet.se", clicks: ["//button[text()='Godkänn alla cookies']"] },
  { name: "cmp.svd.se", clicks: ["//button[text()='Jag förstår']"] },
  { name: "cmp.omni.se", clicks: ["//button[text()='Okej']"] },
  { name: "api.tinypass.com", clicks: ["//button[@aria-label='Close']"] },
  { name: "cmpv2.independent.co.uk", clicks: ["//button[text()='AGREE']"] },
  { name: "cmp.dpgmedia.nl", clicks: ["//button[text()='Akkoord']"] },
  { name: "richmedia.cdnservices.net", clicks: "//h1[text()='TILL REALTID']" },
  { name: "consent-cdn.zeit.de", clicks: ["//button[text()='ACCEPT AND CONTINUE']"] },
  { name: "cmp.hln.be", clicks: ["//button[text()='Akkoord']"] },
  { name: "cmp.dpgmedia.be", clicks: ["//button[text()='Akkoord']"] },
  { name: "sourcepointcmp.bloomberg.com", clicks: ["//button[text()='Yes, I Accept']"] },
];

if (typeof module !== "undefined") {
  module.exports = { siteActions, iframeActions, defaultWidth, defaultDelay, defaultPostDelay };
}
